### PR TITLE
guest, home, login, profile, and signup handlebars, profile.js, modif…

### PR DESCRIPTION
**Pull request by EvelynMS1**
…ied Controllers/homeRoutes.js, profile.css needs code

### CODE REVIEW

**Review by EvelynMS1 — COMMENTED** [review]
replacing render object

**Review by EvelynMS1 — COMMENTED** [review]
added handlebars for each page, changed handlebar path for rendering, from test to home and added an additional handlebar, login handlebar.

**Review by EvelynMS1 — COMMENTED** [review]
viewed files

**Review by ag-harry — APPROVED** [review]
Commit 2nd review

**Review by ag-harry — APPROVED** [review]
3rd time

**Comment by ag-harry** [comment]
attempt to fix commit issue with index.html

**Pull request merged**
